version: '3'

services:

  dbService:
    image: mysql/mysql-server:8.0
    cap_add:
      - SYS_NICE

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recipeApp
      - MYSQL_USER=recipe
      - MYSQL_PASSWORD=Pass1234
    networks:
      - recipe-network
    ports:
      - 3307:3306
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  recipe-app:
    image: recipe
    restart: on-failure
    depends_on:
      - dbService
    ports:
      - 9000:9000
    environment:
      - DATABASE_HOST=dbService
      - DATABASE_USER=recipe
      - DATABASE_PASSWORD=Pass1234
      - DATABASE_NAME=recipeApp
      - DATABASE_PORT=3307
    networks:
      - recipe-network

networks:
    recipe-network :